apiVersion: v1
kind: Service
metadata:
  name: greenhouse
  labels:
    app: greenhouse
spec:
  ports:
    - port: 8080
  selector:
    app: greenhouse
    tier: frontend
  type: LoadBalancer
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: greenhouse
  labels:
    app: greenhouse
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: greenhouse
        tier: frontend
    spec:
      containers:
      - image: miracleregistry.azurecr.io/greenhouse:14
        imagePullPolicy: Always
        name: greenhouse
        ports:
          - containerPort: 8080
      imagePullSecrets:
        - name: dockersecret
